package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/reallyoldfogie/mc-agent/agent"
	"github.com/reallyoldfogie/mc-agent/config"
	_ "github.com/reallyoldfogie/mc-agent/handler_versions"
	"github.com/reallyoldfogie/mc-agent/internal/llm"
	"github.com/reallyoldfogie/mc-agent/models"
	"github.com/reallyoldfogie/mc-agent/utils"

	rof_utils "github.com/reallyoldfogie/mc-bot-go/utils"

	"gopkg.in/natefinch/lumberjack.v2"
)

// envPrefix is this command's ENV-override prefix (config.ApplyEnv's
// second layer, docs/plans/UNIFIED_CONFIG_PLAN.md) — e.g.
// MCAGENT_CONNECTION_ADDRESS.
const envPrefix = "MCAGENT"

var (
	actionsJSONPath = flag.String("actions", "actions.json", "Path to actions.json (generated by geniface)")

	configPath *string
	connOv     *config.ConnectionFlagOverrides
	replayOv   *config.ReplayFlagOverrides
	skinOv     *config.SkinFlagOverrides
	movementOv *config.MovementFlagOverrides

	help = flag.Bool("help", false, "Display help")
)

func init() {
	configPath = config.RegisterConfigPathFlag(flag.CommandLine)
	connOv = config.RegisterConnectionFlags(flag.CommandLine)
	replayOv = config.RegisterReplayFlags(flag.CommandLine)
	skinOv = config.RegisterSkinFlags(flag.CommandLine)
	movementOv = config.RegisterMovementFlags(flag.CommandLine)
}

type BlockPos struct {
	Pos       models.V3 `json:"pos,omitempty"`
	BlockName string    `json:"block_name,omitempty"`
	Distance  float64   `json:"distance,omitempty"`
}

// --------------------
// Game State Builder
// --------------------

type tmpSlot struct {
	SlotIndex int    `json:"slot_index"`
	ID        int32  `json:"id"`
	Count     int32  `json:"count"`
	Name      string `json:"name"`
}

func buildGameStateString(goal string, agent models.Agent, blocks []BlockPos, radius int, lastResult string, lastPath *models.Path) string {
	pos, initialized := agent.GetPositionSimple()
	if !initialized {
		return ""
	}
	x, y, z := pos.X, pos.Y, pos.Z

	const miningRange = 3.0

	itemMgr := agent.GetItemManager()
	inventoryRaw := agent.GetInventory().GetSlots()
	inventory := []tmpSlot{}
	for idx, slot := range inventoryRaw {
		if slot.ID != 0 {
			itemName := itemMgr.GetItemNameByID(int32(slot.ID))
			log.Printf("Inventory slot %d: %s x %d", idx, itemName, slot.Count)
			inventory = append(inventory, tmpSlot{SlotIndex: idx, ID: int32(slot.ID), Count: int32(slot.Count), Name: itemName})
		} else {
			log.Printf("Inventory slot %d: empty", idx)
		}
	}
	inventoryRawStr, _ := json.Marshal(inventory)
	inventoryStr := string(inventoryRawStr)

	// Categorize blocks by mining range
	mineableBlocks := []BlockPos{}
	pathfindingBlocks := []BlockPos{}
	for _, b := range blocks {
		if b.Distance <= miningRange {
			mineableBlocks = append(mineableBlocks, b)
		} else {
			pathfindingBlocks = append(pathfindingBlocks, b)
		}
	}

	// Sort each category by distance
	sort.Slice(mineableBlocks, func(i, j int) bool {
		return mineableBlocks[i].Distance < mineableBlocks[j].Distance
	})
	sort.Slice(pathfindingBlocks, func(i, j int) bool {
		return pathfindingBlocks[i].Distance < pathfindingBlocks[j].Distance
	})

	mineableStr := "[]"
	if len(mineableBlocks) > 0 {
		mineableBytes, _ := json.Marshal(mineableBlocks)
		mineableStr = string(mineableBytes)
	}

	pathfindingStr := "[]"
	if len(pathfindingBlocks) > 0 {
		pathfindingBytes, _ := json.Marshal(pathfindingBlocks)
		pathfindingStr = string(pathfindingBytes)
	}

	fmt.Printf("[buildPrompt] Mineable blocks (≤%.1f): %v\n", miningRange, mineableStr)
	fmt.Printf("[buildPrompt] Pathfinding blocks (>%.1f): %v\n", miningRange, pathfindingStr)

	pathInfo := "none"
	if lastPath != nil && lastPath.Found {
		pathInfo = fmt.Sprintf("from (%.1f, %.1f, %.1f) to (%.1f, %.1f, %.1f), %d steps — ready to execute",
			lastPath.StartPos.X, lastPath.StartPos.Y, lastPath.StartPos.Z,
			lastPath.GoalPos.X, lastPath.GoalPos.Y, lastPath.GoalPos.Z,
			len(lastPath.Steps))
	}

	mineableBlocksDisplay := mineableStr
	if mineableStr == "[]" {
		mineableBlocksDisplay = "(none available)"
	}

	pathfindingBlocksDisplay := pathfindingStr
	if pathfindingStr == "[]" {
		pathfindingBlocksDisplay = "(none available)"
	}

	return fmt.Sprintf(`Goal: %s

Current State:
- Current Position: (X: %.2f, Y: %.2f, Z: %.2f)
- Precomputed Path: %s
- Last Result: %s
- Current Inventory: %s

MINEABLE BLOCKS (distance ≤ 3 blocks, mine immediately):
%s

PATHFINDING BLOCKS (distance > 3 blocks, pathfind to them):
%s

Strategy:
- If mineable blocks exist (distance ≤ 3), mine the closest one immediately
- Only pathfind to blocks when NO mineable blocks exist
- If a precomputed path is ready to execute, execute it next unless new mineable blocks appeared
`, goal, x, y, z, pathInfo, lastResult, inventoryStr, mineableBlocksDisplay, pathfindingBlocksDisplay)
}

const (
	// model = "llama3.2" // older, larger, more expensive, but may perform better on complex tasks
	model = "phi4-mini" // smaller, faster and newer, but may struggle with complex reasoning (currently best for simple tasks and fast iteration
)

// --------------------
// Main Loop
// --------------------

func main() {
	const numIterations = 5

	flag.Parse()

	if *help {
		flag.PrintDefaults()
		return
	}

	// Load actions.json
	specBytes, err := os.ReadFile(*actionsJSONPath)
	if err != nil {
		log.Fatalf("failed to load actions.json: %v", err)
	}

	var agentSpec llm.AgentSpec
	if err := json.Unmarshal(specBytes, &agentSpec); err != nil {
		log.Fatalf("failed to parse actions.json: %v", err)
	}

	// Create a timeout context for the entire operation
	timeoutCtx, timeoutCancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer timeoutCancel()

	// Start agent with timeout context so it respects the deadline
	// getAgent returns agentCtx which is a child context that honors both timeout and signals
	a, agentCtx, agentCancel := getAgent(timeoutCtx)
	defer func() {
		// Give cleanup a generous time for recorder flush (30 seconds).
		// Recorder.Close() may need time to write buffered packets to disk.
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cleanupCancel()

		a.Close(cleanupCtx)
		agentCancel()
	}()

	// wait for agent to be initialize and world to load
	time.Sleep(5 * time.Second)

	// Build LLM subsystem
	ollamaLLM := llm.NewOllamaClient(model)
	agentExecutor := agent.NewLLMExecutor(a)

	goal := "Find a tree and mine any kind of log (blocks whose name contains 'log')"
	lastResult := ""
	var lastPath *models.Path

	blockFilter := "log"
	a.SendChat(fmt.Sprintf("Agent initialized. Goal: %s. Looking for blocks with '%s' in their name around the agent to inform action selection.", goal, blockFilter))
	blockPos, radius, err := getSurroundingBlocksOfType(agentCtx, a, blockFilter)
	if err != nil {
		log.Printf("Error getting surrounding blocks: %v", err)
		panic(err)
	}

LOOP:
	for cnt := range numIterations {
		gameState := buildGameStateString(goal, a, blockPos, radius, lastResult, lastPath)

		log.Printf("Built game state for iteration %d (len=%d)", cnt, len(gameState))
		if gameState == "" {
			continue
		}

		a.SendChat("Thinking...")

		// Build full prompt using the LLM subsystem
		fullPrompt := llm.BuildAgentPrompt(agentSpec, goal, gameState)
		promptBytes := []byte(fullPrompt)

		// Call LLM via the Client interface
		respBytes, err := ollamaLLM.Call(agentCtx, promptBytes)
		if err != nil {
			log.Println("LLM error:", err)
			a.SendChat(fmt.Sprintf("LLM error: %v", err))
			continue
		}

		// Parse the LLM response
		var actionCall struct {
			Name string         `json:"name"`
			Args map[string]any `json:"args"`
		}

		if err := json.Unmarshal(respBytes, &actionCall); err != nil {
			log.Printf("Failed to parse LLM response: %v\nRaw: %s", err, string(respBytes))
			a.SendChat(fmt.Sprintf("Failed to parse LLM response: %v", err))
			continue
		}

		log.Printf("LLM action (%d): name=%s, args=%v", cnt, actionCall.Name, actionCall.Args)
		a.SendChat(fmt.Sprintf("Executing action: %s", actionCall.Name))

		// Create executor state with current lastPath
		execState := &agent.AgentExecutorState{
			LastPath: lastPath,
		}

		// Execute the action via the executor
		result, err := agentExecutor.Execute(agentCtx, actionCall.Name, actionCall.Args, execState)
		if err != nil {
			log.Printf("Action execution failed: %v", err)
			lastResult = fmt.Sprintf("⚠️ Execution error: %v", err)
		} else {
			lastResult = fmt.Sprintf("%v", result)
			// Update lastPath if FindPath returned a path
			if actionCall.Name == "FindPath" {
				if path, ok := result.(*models.Path); ok {
					lastPath = path
					log.Printf("Updated lastPath: %d steps", len(path.Steps))
				}
			}
		}

		a.SendChat(lastResult)
		log.Printf("Action result (%d): %s", cnt, lastResult)

		time.Sleep(2 * time.Second)

		a.SendChat("Observing surroundings...")
		blockPos, radius, err = getSurroundingBlocksOfType(agentCtx, a, blockFilter)
		if err != nil {
			log.Printf("Error getting surrounding blocks: %v", err)
			panic(err)
		}

		select {
		case <-agentCtx.Done():
			log.Printf("Timeout reached or signal received, exiting main loop")
			break LOOP
		default:
			continue
		}
	}

	log.Printf("Main loop exited, waiting for agent to finish cleanup")
	log.Printf("Agent closed successfully")
}

func getAgent(ctx context.Context) (models.Agent, context.Context, context.CancelFunc) {
	settings, err := config.Load(*configPath)
	if err != nil {
		log.Fatalf("%v", err)
	}
	if err := config.ApplyEnv(&settings, envPrefix); err != nil {
		log.Fatalf("%v", err)
	}
	config.ApplyConnectionFlags(&settings.Connection, flag.CommandLine, connOv)
	config.ApplyReplayFlags(&settings.Replay, flag.CommandLine, replayOv)
	config.ApplySkinFlags(&settings.Skin, flag.CommandLine, skinOv)
	config.ApplyMovementFlags(&settings.Movement, flag.CommandLine, movementOv)

	// Build Auth from flags (offline mode) or Microsoft authentication
	// (cached under settings.Auth.CacheDir) — see agent.ResolveAuth's doc
	// comment.
	auth, err := agent.ResolveAuth(settings.Connection.Offline, settings.Connection.Name, settings.Connection.UUID, settings.Connection.Token, settings.Auth)
	if err != nil {
		log.Fatalf("%v", err)
	}
	if settings.Connection.Offline {
		fmt.Printf("Offline mode => using name=%s uuid=%s\n", auth.Name, auth.UUID)
	} else {
		log.Printf("Authenticated as %s (%s)", auth.Name, auth.UUID)
	}

	// Create skin provider for replay texture embedding
	skinProvider := agent.NewSkinFetcher(agent.SkinFetcherConfig{
		AllowNetwork: settings.Skin.AllowNetwork,
		CacheRoot:    settings.Skin.CacheDir,
		HTTPClient:   &http.Client{Timeout: 3 * time.Second},
	})

	// Prepare rotating log for packet logging
	cacheDir, err := utils.FindOrCreateCacheDir()
	if err != nil {
		log.Fatalf("find cache directory: %v", err)
	}
	packetLogsDir := filepath.Join(cacheDir, "logs", "packets")
	_ = os.MkdirAll(packetLogsDir, 0760)
	packetLogWriter := &lumberjack.Logger{
		Filename:   filepath.Join(packetLogsDir, auth.Name+"_"+time.Now().Format("20060102_150405")+".log"),
		MaxSize:    10,
		MaxBackups: 3,
		MaxAge:     28,
		Compress:   true,
		LocalTime:  true,
	}

	log.Printf("Packet log: %s", packetLogWriter.Filename)

	// auto-detect version (if not provided)
	if settings.Connection.Version == "" {
		detectedVersion, _, err := rof_utils.CheckServerVersion(settings.Connection.Address, 0)
		if err != nil {
			panic(fmt.Sprintf("auto-detect version from %s failed: %v", settings.Connection.Address, err))
		}
		settings.Connection.Version = detectedVersion
	}

	if settings.Replay.Output == "" {
		replayDir := filepath.Join(cacheDir, "replays", settings.Connection.Version)
		settings.Replay.Output = filepath.Join(replayDir, auth.Name+"_"+time.Now().Format("20060102_150405")+".mcpr")
	}

	// Build agent config - version detection, manager resolution, and client creation
	// are now handled automatically by agent.Init() if not provided
	cfg := models.AgentConfig{
		Name:                 auth.Name, // Use authenticated name
		Address:              settings.Connection.Address,
		Version:              settings.Connection.Version, // Empty = auto-detect from server
		Auth:                 auth,
		MCDataGenPath:        settings.Connection.MCDataGenPath,
		MCProtocolGoPath:     settings.Connection.MCProtocolGoPath,
		EnableClutchAssist:   settings.Movement.EnableClutch,
		StopFilePath:         ".agentStop", // Enable graceful shutdown via stop file
		EnableReplay:         true,         // settings.Replay.Enable — kept forced on, matching this command's pre-existing behavior (preserved as-is during the config-unification rewrite, not a decision made here)
		ReplayOutput:         settings.Replay.Output,
		ReplayGenerator:      settings.Replay.Generator,
		SkinProvider:         skinProvider,
		LogWriter:            packetLogWriter,
		PathfinderGoalRadius: 3.0,
	}

	a, err := agent.New(cfg)
	if err != nil {
		log.Fatalf("failed creating agent: %v", err)
	}

	newCtx, cancel := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM)
	if err := a.Init(ctx); err != nil {
		log.Fatalf("init failed: %v", err)
	}

	if err := a.Start(ctx); err != nil {
		log.Fatalf("start failed: %v", err)
	}
	return a, newCtx, cancel
}

func getSurroundingBlocksOfType(ctx context.Context, agent models.Agent, filterKeep string) ([]BlockPos, int, error) {
	const radiusStep = 16
	radius := 0
	radiusExpansionLoop := 3
	var err error
	blocks := []BlockPos{}

	for range radiusExpansionLoop {
		radius += radiusStep
		blocks, err = getSurroundingBlocksOfTypeWithinRadius(ctx, agent, filterKeep, radius)
		if err != nil {
			return nil, 0, err
		}

		if len(blocks) > 0 {
			break
		}

		fmt.Printf("[getSurroundingBlocksOfType] No blocks of type %s found within radius %d, increasing radius and retrying...\n", filterKeep, radius)

		select {
		case <-ctx.Done():
			return nil, 0, fmt.Errorf(`context cancelled while searching for blocks [filter="%s"]: %v`, filterKeep, ctx.Err())
		default:
			continue
		}

	}

	fmt.Printf("[getSurroundingBlocksOfType] Found %d blocks of type %s around agent\n", len(blocks), filterKeep)
	return blocks, radius, nil
}

// if filterKeep is non-empty, only blocks whose names contain filterKeep will be returned, otherwise if filterKeep is empty, all blocks will be returned
func getSurroundingBlocksOfTypeWithinRadius(ctx context.Context, agent models.Agent, filterKeep string, radius int) ([]BlockPos, error) {
	visibleBlocks, err := agent.FindAllVisibleBlocksInSphere(ctx, radius)
	if err != nil {
		return nil, err
	}

	agentPos, initialized := agent.GetPositionSimple()
	if !initialized {
		return nil, fmt.Errorf("agent position not initialized")
	}

	blocks := []BlockPos{}

	fmt.Printf("[getSurroundingBlocksOfTypeWithinRadius] Scanning (len=%d) %#v visible blocks within radius %d for type '%s'...\n", len(visibleBlocks), visibleBlocks, radius, filterKeep)

	for _, vb := range visibleBlocks {
		blockName := vb.BlockName
		if filterKeep != "" {
			if !strings.Contains(blockName, filterKeep) {
				fmt.Printf("[getSurroundingBlocksOfTypeWithinRadius (radius: %d)] Skipping block at (%d, %d, %d) with name '%s' (does not contain '%s')\n", radius, vb.X, vb.Y, vb.Z, blockName, filterKeep)
				continue
			}
			fmt.Printf("[getSurroundingBlocksOfTypeWithinRadius (radius: %d)] Found block of type '%s' at (%d, %d, %d)\n", radius, blockName, vb.X, vb.Y, vb.Z)
		}

		blockPos := models.V3{X: float64(vb.X), Y: float64(vb.Y), Z: float64(vb.Z)}
		blocks = append(blocks, BlockPos{
			Pos:       blockPos,
			BlockName: blockName,
			Distance:  blockPos.DistanceTo(agentPos),
		})
	}

	// var blocks []BlockPos
	// for ix := -8; ix <= 8; ix++ {
	// 	for iy := -3; iy <= 3; iy++ {
	// 		for iz := -8; iz <= 8; iz++ {
	// 			blockName := agent.BlockNameAt(int(x)+ix, int(y)+iy, int(z)+iz)
	// 			if !strings.Contains(blockName, filterKeep) {
	// 				fmt.Printf("[getSurroundingBlocksOfType] Skipping block at (%d, %d, %d) with name '%s' (does not contain '%s')\n", int(x)+ix, int(y)+iy, int(z)+iz, blockName, filterKeep)
	// 				continue
	// 			}
	// 			fmt.Printf("[getSurroundingBlocksOfType] Found block of type '%s' at (%d, %d, %d)\n", blockName, int(x)+ix, int(y)+iy, int(z)+iz)
	// 			blocks = append(blocks, BlockPos{
	// 				Pos:       models.V3{X: float64(int(x) + ix), Y: float64(int(y) + iy), Z: float64(int(z) + iz)},
	// 				BlockName: blockName,
	// 			})
	// 		}
	// 	}
	// }
	return blocks, nil
}
